version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /prettier
    ignore:
      - dependency-name: node
        versions: [23, 25, 27, 29, 31]
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /prettier
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /markdownlint
    ignore:
      - dependency-name: node
        versions: [23, 25, 27, 29, 31]
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /markdownlint
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /yamllint
    ignore:
      - dependency-name: python
        update-types: [version-update:semver-patch]
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /yamllint
    schedule:
      interval: monthly
