version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/prettier"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/prettier"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/markdownlint"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/markdownlint"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/yamllint"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/yamllint"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/jsonlint"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/jsonlint"
    schedule:
      interval: "daily"
