version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/prettier"
    ignore:
      - dependency-name: "node"
        versions: ["17", "19", "21", "23", "25"]
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/prettier"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/markdownlint"
    ignore:
      - dependency-name: "node"
        versions: ["17", "19", "21", "23", "25"]
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/markdownlint"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/yamllint"
    ignore:
      - dependency-name: "python"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/yamllint"
    schedule:
      interval: "daily"
