changelog:
  exclude:
    labels:
      - github
      - docs
      - chore
    authors:
      - dependabot[bot]
  categories:
    - title: BREAKING CHANGES
      labels:
        - breaking-change
    - title: ENHANCEMENTS
      labels:
        - docker
    - title: NEW FEATURES
      labels:
        - "*"
