name: Push Docker
description: Extract metadata, log in, build, and push Docker image.

inputs:
  name:
    required: true
    description: "The name of the building docker image."
  description:
    required: true
    description: "The description of the building docker image."
  version:
    required: true
    description: "The version of the building docker image."
  username:
    required: true
    description: "Username used to log against the Docker registry."
  dockerhub-token:
    required: true
    description: "Personal access token used to log against Docker Hub."
  github-token:
    required: true
    description: "GITHUB_TOKEN used to log against the Docker registry."
  push:
    required: true
    description: "The flag to enable/disable docker push. Specify false for build only."

runs:
  using: composite

  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ inputs.username }}/${{ inputs.name }}
          ghcr.io/${{ github.repository }}/${{ inputs.name }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ inputs.version }}
        labels: |
          org.opencontainers.image.title=${{ inputs.name }}
          org.opencontainers.image.description=${{ inputs.description }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      if: ${{ inputs.push == 'true' }}
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      if: ${{ inputs.push == 'true' }}
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.github-token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.name }}/
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "package"
  color: "gray-dark"
