name: Lint Docker
on:
  workflow_dispatch:
  pull_request:
    paths: ["**/Dockerfile", ".github/workflows/lint-docker.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  hadolint:
    name: Lint by hadolint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Install
        id: install
        run: |
          set -x
          image="hadolint/hadolint"
          echo "image=${image}" >> "${GITHUB_OUTPUT}"
          docker pull "${image}"

      - name: Show version
        env:
          IMAGE: ${{ steps.install.outputs.image }}
        run: |
          set -x
          docker run --interactive --rm --read-only --user 1111:1111 \
            --security-opt no-new-privileges --cap-drop all --network none \
            "${IMAGE}" hadolint --version

      - name: Run
        env:
          IMAGE: ${{ steps.install.outputs.image }}
        run: |
          set -x
          docker run --interactive --rm --read-only --user 1111:1111 \
            --security-opt no-new-privileges --cap-drop all --network none \
            --volume "${PWD}:${PWD}" --workdir "${PWD}" \
            "${IMAGE}" hadolint ./**/Dockerfile
