name: Lint Docker
on:
  workflow_dispatch:
    inputs:
      pull-request-number:
        type: string
        required: true
        description: The pull request number to check for Dockerfile linting issues.
  pull_request:
    paths: ["**/Dockerfile", ".github/workflows/lint-docker.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  dispatch:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      is-prettier: ${{ steps.diff.outputs.is-prettier }}
      is-yamllint: ${{ steps.diff.outputs.is-yamllint }}
      is-markdownlint: ${{ steps.diff.outputs.is-markdownlint }}
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: tmknom/secure-checkout-action@v1

      - name: Describe diff
        id: diff
        env:
          PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number || github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          diff_dirs="$(gh api \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GITHUB_REPOSITORY}/pulls/${PULL_REQUEST_NUMBER}/files" \
            --jq '.[].filename' | \
            xargs -n1 dirname | \
            sort -u)"

          if grep -q '^yamllint$' <<< "${diff_dirs}"; then
            echo "is-yamllint=true" >> "${GITHUB_OUTPUT}"
          fi

          if grep -q '^prettier$' <<< "${diff_dirs}"; then
            echo "is-prettier=true" >> "${GITHUB_OUTPUT}"
          fi

          if grep -q '^markdownlint$' <<< "${diff_dirs}"; then
            echo "is-markdownlint=true" >> "${GITHUB_OUTPUT}"
          fi

  hadolint:
    name: Lint by hadolint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Secure hadolint
        uses: tmknom/secure-hadolint-action@bc9a12ff7ee12b95e2a4e43bcb01d86545843688 # v0.4.2

  dockle:
    name: Lint by Dockle
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [dispatch]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Secure Dockle for yamllint
        if: ${{ needs.dispatch.outputs.is-yamllint == 'true' }}
        uses: tmknom/secure-dockle-action@c07e7b3b7abd3b479ccd84762487ebbe78116735 # v0.2.2
        with:
          dockerfile-path: yamllint/Dockerfile

      - name: Secure Dockle for prettier
        if: ${{ needs.dispatch.outputs.is-prettier == 'true' }}
        uses: tmknom/secure-dockle-action@c07e7b3b7abd3b479ccd84762487ebbe78116735 # v0.2.2
        with:
          dockerfile-path: prettier/Dockerfile

      - name: Secure Dockle for markdownlint
        if: ${{ needs.dispatch.outputs.is-markdownlint == 'true' }}
        uses: tmknom/secure-dockle-action@c07e7b3b7abd3b479ccd84762487ebbe78116735 # v0.2.2
        with:
          dockerfile-path: markdownlint/Dockerfile
