name: Lint Docker
on:
  workflow_dispatch:
  pull_request:
    paths: ["**/Dockerfile", ".github/workflows/lint-docker.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  hadolint:
    name: Lint by hadolint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Secure hadolint
        uses: tmknom/secure-hadolint-action@1462a50f9d12f500dcde21427e817c4e30560782 # v0.4.0

  dockle:
    name: Lint by Dockle
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Secure Dockle for yamllint
        uses: tmknom/secure-dockle-action@c07e7b3b7abd3b479ccd84762487ebbe78116735 # v0.2.2
        with:
          dockerfile-path: yamllint/Dockerfile

      - name: Secure Dockle for prettier
        uses: tmknom/secure-dockle-action@c07e7b3b7abd3b479ccd84762487ebbe78116735 # v0.2.2
        with:
          dockerfile-path: prettier/Dockerfile

      - name: Secure Dockle for markdownlint
        uses: tmknom/secure-dockle-action@c07e7b3b7abd3b479ccd84762487ebbe78116735 # v0.2.2
        with:
          dockerfile-path: markdownlint/Dockerfile
