name: Lint Markdown
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/lint-markdown.yml"
  pull_request:
    paths:
      - "**.md"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    uses: tmknom/workflows/.github/workflows/lint-markdown.yml@v1
    with:
      markdownlint-config: ".markdownlint.yml"
