name: Lint Action
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/lint-action.yml"
  pull_request:
    paths:
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"
      - "!.github/workflows/lint-action.yml"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  diff:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      files: ${{ steps.git-diff.outputs.files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Git diff
        uses: ./.github/actions/git_diff
        id: git-diff
        with:
          type: "action"

  lint-action:
    uses: tmknom/workflows/.github/workflows/lint-action.yml@v1
    needs: [diff]
    if: ${{ needs.diff.outputs.files }}
    with:
      actionlint-ignore-options: >
        "permissions" section should not be empty.
