name: Lint Docker
on:
  workflow_dispatch:
  pull_request:
    paths: ["**/Dockerfile", ".github/workflows/lint-docker.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  hadolint:
    name: Lint by hadolint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Secure hadolint
        uses: tmknom/secure-hadolint-action@6b2beed052633600c936710c20c400e4883c188f # v0.2.0

  dockle:
    name: Lint by Dockle
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Secure Dockle for yamllint
        uses: tmknom/secure-dockle-action@de64904abbaee35da28dd45cfa7a31e084347ed3 # v0.2.0
        with:
          dockerfile-path: yamllint/Dockerfile

      - name: Secure Dockle for prettier
        uses: tmknom/secure-dockle-action@de64904abbaee35da28dd45cfa7a31e084347ed3 # v0.2.0
        with:
          dockerfile-path: prettier/Dockerfile

      - name: Secure Dockle for markdownlint
        uses: tmknom/secure-dockle-action@de64904abbaee35da28dd45cfa7a31e084347ed3 # v0.2.0
        with:
          dockerfile-path: markdownlint/Dockerfile
