name: Lint Action
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/lint-action.yml"
  pull_request:
    paths:
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-action:
    uses: tmknom/workflows/.github/workflows/lint-action.yml@v1
    with:
      actionlint-ignore-options: >
        "permissions" section should not be empty.
