name: prettier
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "prettier/*"
      - ".github/workflows/prettier.yml"
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: prettier

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint-docker.yml
    with:
      dockerfile: prettier/Dockerfile

  metadata:
    name: Extract metadata
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Describe version
        id: version
        run: |
          semver="$(jq -r ".dependencies.${IMAGE_NAME}" ./"${IMAGE_NAME}"/package.json)"
          echo "::set-output name=semver::${semver}"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.version.outputs.semver }}

  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [lint, metadata]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.IMAGE_NAME }}/
          push: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
          tags: ${{ needs.metadata.outputs.tags }}
          labels: ${{ needs.metadata.outputs.labels }}
