name: Release yamllint
on:
  workflow_dispatch:
    inputs:
      push:
        type: choice
        required: true
        description: "The flag to docker push."
        default: "false"
        options:
          - "true"
          - "false"
  pull_request:
    paths:
      - "yamllint/*"
      - ".github/workflows/release-yamllint.yml"
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: yamllint
  REGISTRY: ghcr.io

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Describe version
        id: describe
        run: |
          semver="$(cut -d '=' -f 3 "${IMAGE_NAME}"/requirements.txt)"
          echo "::set-output name=semver::${semver}"

      - name: Push Docker
        uses: ./.github/actions/docker_push/
        with:
          image-name: ${{ env.IMAGE_NAME }}
          image-description: "Dockernized yamllint, it's a linter for YAML files."
          images: |
            ${{ github.actor }}/${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          metadata-tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.describe.outputs.semver }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          context: ${{ env.IMAGE_NAME }}/
          push: >-
            ${{
              (github.event_name == 'workflow_dispatch' && github.event.inputs.push == 'true')
              || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
            }}
