name: Release prettier
on:
  workflow_dispatch:
    inputs:
      push:
        type: choice
        required: true
        description: The flag to docker push.
        options:
          - 'true'
          - 'false'
        default: 'true'
  push:
    branches: [main]
    paths: ['prettier/package.json']

concurrency: ${{ github.workflow }}

permissions: {}

jobs:
  extract:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      version: ${{ steps.extract.outputs.version }}
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Extract version
        id: extract
        run: |
          set -x
          version="$(jq -r ".dependencies.prettier" prettier/package.json)"
          echo "version=${version}" >> "${GITHUB_OUTPUT}"

  release:
    needs: [extract]
    uses: ./.github/workflows/reusable-release.yml
    with:
      name: prettier
      description: Dockernized prettier, it's an opinionated code formatter.
      version: ${{ needs.extract.outputs.version }}
      push: ${{ inputs.push || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
      pull-requests: write
