name: Push Docker
on:
  workflow_call:
    inputs:
      images:
        required: true
        type: string
        description: "List of Docker images to use as base name for tags."
      metadata-tags:
        required: true
        type: string
        description: "List of tags as key-value pair attributes."
      registry:
        required: false
        type: string
        description: "Server address of Docker registry. If not set then will default to Docker Hub."
      username:
        required: true
        type: string
        description: "Username used to log against the Docker registry."
      context:
        default: "."
        required: false
        type: string
        description: "Build's context is the set of files located in the specified PATH or URL."
      push:
        required: true
        type: string
        description: "The flag to enable/disable docker push. Specify false for build only."
    secrets:
      password:
        required: true
        description: "Password or personal access token used to log against the Docker registry."

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.images }}
          tags: ${{ inputs.metadata-tags }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.password }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
