name: Lint Docker
on:
  workflow_call:
    inputs:
      dockerfile:
        default: "**/Dockerfile"
        required: false
        type: string
        description: "Path to a Dockerfile."

jobs:
  hadolint:
    name: Lint by hadolint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull hadolint
        run: |
          docker pull hadolint/hadolint
      - name: Display hadolint
        run: |
          docker run --rm -v "$(pwd)":/work -w /work \
          --security-opt=no-new-privileges --cap-drop all --network none \
          hadolint/hadolint hadolint --version
      - name: Run hadolint
        env:
          DOCKERFILE: ${{ inputs.dockerfile }}
        run: |
          set -x
          docker run --rm -v "$(pwd)":/work -w /work \
          --security-opt=no-new-privileges --cap-drop all --network none \
          hadolint/hadolint hadolint "${DOCKERFILE}"

  dockerfilelint:
    name: Lint by dockerfilelint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull dockerfilelint
        run: |
          docker pull replicated/dockerfilelint
      - name: Display dockerfilelint
        run: |
          docker run --rm -v "$(pwd)":/work -w /work \
          --security-opt=no-new-privileges --cap-drop all --network none \
          replicated/dockerfilelint --version
      - name: Run dockerfilelint
        env:
          DOCKERFILE: ${{ inputs.dockerfile }}
        run: |
          set -x
          docker run --rm -v "$(pwd)":/work -w /work \
          --security-opt=no-new-privileges --cap-drop all --network none \
          replicated/dockerfilelint "${DOCKERFILE}"
