name: Test yamllint
on:
  workflow_dispatch:
  pull_request:
    paths: ["yamllint/*", ".github/workflows/test-yamllint.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup
        run: |
          set -x
          docker build -t local/sut yamllint/

          cat <<EOF > test.yml
          ---
          name: valid
          description: This is a valid basic yaml file.
          EOF

      - name: Exercise
        id: exercise
        run: |
          set -x
          docker run --interactive --rm --read-only --user nonroot:nonroot \
            --security-opt no-new-privileges --cap-drop all --network none \
            --volume "${PWD}:${PWD}" --workdir "${PWD}" \
            local/sut --strict test.yml
        continue-on-error: true

      - name: Verify
        env:
          OUTCOME: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${OUTCOME}" = "success"

  test-error:
    name: Test error
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup
        run: |
          set -x
          docker build -t local/sut yamllint/

          cat <<EOF > test.yml
          ---
          name: invalid
          description:  |
            This is an invalid basic yaml file.
          EOF

      - name: Exercise
        id: exercise
        run: |
          set -x
          docker run --interactive --rm --read-only --user nonroot:nonroot \
            --security-opt no-new-privileges --cap-drop all --network none \
            --volume "${PWD}:${PWD}" --workdir "${PWD}" \
            local/sut --strict test.yml
        continue-on-error: true

      - name: Verify
        env:
          OUTCOME: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${OUTCOME}" = "failure"
