name: yamllint
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "yamllint/*"
      - ".github/workflows/yamllint.yml"
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: yamllint
  REGISTRY: ghcr.io

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint-docker.yml
    with:
      dockerfile: yamllint/Dockerfile

  constants:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      semver: ${{ steps.describe.outputs.semver }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Describe version
        id: describe
        run: |
          semver="$(cut -d '=' -f 3 yamllint/requirements.txt)"
          echo "::set-output name=semver::${semver}"

  push:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [lint, constants]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Push Docker
        uses: ./.github/actions/docker_push/
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          metadata-tags: |
            type=raw,value=latest
            type=raw,value=${{ needs.constants.outputs.semver }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ env.IMAGE_NAME }}/
          push: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
